spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_prod?serverTimezone=Europe/Moscow&useSSL=false
    username: sfg_prod_user
    password: guru
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    show-sql: false